
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: MFS Parameters
*
*******************************************************************/

#ifndef _MFS_CONFIG_H
#define _MFS_CONFIG_H
#include <xilmfs.h>
#define MFS_NUMBYTES  100000
#define MFS_BASE_ADDRESS 0x10000
#define MFS_INIT_TYPE  MFSINIT_NEW
#endif
