# FPGA Pin Mapping for AMDC REV D
#
# Please keep this document in sync with
# the documentation in the AMDC-Hardware
# repo: docs/PinMappingRevD.md


###########
# RGB LED #
###########

set_property IOSTANDARD LVCMOS18 [get_ports {user_led_din[0]}]

set_property PACKAGE_PIN R8 [get_ports {user_led_din[0]}]


###########
# ENCODER #
###########

set_property IOSTANDARD LVCMOS18 [get_ports encoder_1a]
set_property IOSTANDARD LVCMOS18 [get_ports encoder_1b]
set_property IOSTANDARD LVCMOS18 [get_ports encoder_1z]
set_property IOSTANDARD LVCMOS18 [get_ports encoder_2a]
set_property IOSTANDARD LVCMOS18 [get_ports encoder_2b]
set_property IOSTANDARD LVCMOS18 [get_ports encoder_2z]

set_property PACKAGE_PIN A2 [get_ports encoder_1a]
set_property PACKAGE_PIN A1 [get_ports encoder_1b]
set_property PACKAGE_PIN D7 [get_ports encoder_1z]
set_property PACKAGE_PIN D6 [get_ports encoder_2a]
set_property PACKAGE_PIN A5 [get_ports encoder_2b]
set_property PACKAGE_PIN A4 [get_ports encoder_2z]


#########
#  ADC  #
#########

set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_sdo[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports adc_sck]
set_property IOSTANDARD LVCMOS18 [get_ports adc_cnv]
set_property IOSTANDARD LVCMOS18 [get_ports adc_clkout]

set_property PACKAGE_PIN H6 [get_ports adc_cnv]
set_property PACKAGE_PIN D8 [get_ports adc_sck]
set_property PACKAGE_PIN G4 [get_ports adc_clkout]
set_property PACKAGE_PIN H4 [get_ports {adc_sdo[0]}]
set_property PACKAGE_PIN H3 [get_ports {adc_sdo[1]}]
set_property PACKAGE_PIN G3 [get_ports {adc_sdo[2]}]
set_property PACKAGE_PIN G2 [get_ports {adc_sdo[3]}]
set_property PACKAGE_PIN F4 [get_ports {adc_sdo[4]}]
set_property PACKAGE_PIN G6 [get_ports {adc_sdo[5]}]
set_property PACKAGE_PIN F6 [get_ports {adc_sdo[6]}]
set_property PACKAGE_PIN E8 [get_ports {adc_sdo[7]}]


########
# SPI1 #
########

set_property IOSTANDARD LVCMOS18 [get_ports {spi1_sclk[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi1_miso]
set_property IOSTANDARD LVCMOS18 [get_ports {spi1_mosi[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi1_nss[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi1_in]
set_property IOSTANDARD LVCMOS18 [get_ports {spi1_out[0]}]

set_property PACKAGE_PIN B4 [get_ports {spi1_sclk[0]}]
set_property PACKAGE_PIN C6 [get_ports spi1_miso]
set_property PACKAGE_PIN B3 [get_ports {spi1_mosi[0]}]
set_property PACKAGE_PIN C5 [get_ports {spi1_nss[0]}]
set_property PACKAGE_PIN Y14 [get_ports spi1_in]
set_property PACKAGE_PIN A7 [get_ports {spi1_out[0]}]


########
# SPI2 #
########

set_property IOSTANDARD LVCMOS18 [get_ports {spi2_sclk[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi2_miso]
set_property IOSTANDARD LVCMOS18 [get_ports {spi2_mosi[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi2_nss[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi2_in]
set_property IOSTANDARD LVCMOS18 [get_ports {spi2_out[0]}]

set_property PACKAGE_PIN E2 [get_ports {spi2_sclk[0]}]
set_property PACKAGE_PIN D1 [get_ports spi2_miso]
set_property PACKAGE_PIN D2 [get_ports {spi2_mosi[0]}]
set_property PACKAGE_PIN C1 [get_ports {spi2_nss[0]}]
set_property PACKAGE_PIN Y15 [get_ports spi2_in]
set_property PACKAGE_PIN A6 [get_ports {spi2_out[0]}]


########
# SPI3 #
########

set_property IOSTANDARD LVCMOS18 [get_ports {spi3_sclk[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi3_miso]
set_property IOSTANDARD LVCMOS18 [get_ports {spi3_mosi[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi3_nss[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi3_in]
set_property IOSTANDARD LVCMOS18 [get_ports {spi3_out[0]}]

set_property PACKAGE_PIN G8 [get_ports {spi3_sclk[0]}]
set_property PACKAGE_PIN F7 [get_ports spi3_miso]
set_property PACKAGE_PIN G7 [get_ports {spi3_mosi[0]}]
set_property PACKAGE_PIN E7 [get_ports {spi3_nss[0]}]
set_property PACKAGE_PIN V18 [get_ports spi3_in]
set_property PACKAGE_PIN C8 [get_ports {spi3_out[0]}]


########
# SPI4 #
########

set_property IOSTANDARD LVCMOS18 [get_ports {spi4_sclk[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi4_miso]
set_property IOSTANDARD LVCMOS18 [get_ports {spi4_mosi[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {spi4_nss[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports spi4_in]
set_property IOSTANDARD LVCMOS18 [get_ports {spi4_out[0]}]

set_property PACKAGE_PIN AA14 [get_ports {spi4_sclk[0]}]
set_property PACKAGE_PIN B7 [get_ports spi4_miso]
set_property PACKAGE_PIN AA15 [get_ports {spi4_mosi[0]}]
set_property PACKAGE_PIN B6 [get_ports {spi4_nss[0]}]
set_property PACKAGE_PIN W18 [get_ports spi4_in]
set_property PACKAGE_PIN B8 [get_ports {spi4_out[0]}]


#############
# INVERTERS #
#############

set_property IOSTANDARD LVCMOS18 [get_ports {inverter1_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter1_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter1_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter1_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter1_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter1_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter2_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter2_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter2_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter2_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter2_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter2_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter3_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter3_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter3_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter3_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter3_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter3_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter4_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter4_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter4_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter4_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter4_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter4_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter5_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter5_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter5_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter5_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter5_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter5_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter6_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter6_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter6_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter6_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter6_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter6_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter7_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter7_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter7_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter7_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter7_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter7_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter8_pwm[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter8_pwm[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter8_pwm[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter8_pwm[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter8_pwm[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter8_pwm[5]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_a[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_b[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_c[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {inverter_sts_d[7]}]

set_property PACKAGE_PIN J1 [get_ports {inverter1_pwm[0]}]
set_property PACKAGE_PIN J2 [get_ports {inverter1_pwm[1]}]
set_property PACKAGE_PIN M1 [get_ports {inverter1_pwm[2]}]
set_property PACKAGE_PIN M2 [get_ports {inverter1_pwm[3]}]
set_property PACKAGE_PIN H8 [get_ports {inverter1_pwm[4]}]
set_property PACKAGE_PIN M4 [get_ports {inverter1_pwm[5]}]

set_property PACKAGE_PIN R7 [get_ports {inverter2_pwm[0]}]
set_property PACKAGE_PIN P7 [get_ports {inverter2_pwm[1]}]
set_property PACKAGE_PIN L7 [get_ports {inverter2_pwm[2]}]
set_property PACKAGE_PIN K7 [get_ports {inverter2_pwm[3]}]
set_property PACKAGE_PIN M3 [get_ports {inverter2_pwm[4]}]
set_property PACKAGE_PIN N4 [get_ports {inverter2_pwm[5]}]

set_property PACKAGE_PIN U1 [get_ports {inverter3_pwm[0]}]
set_property PACKAGE_PIN U2 [get_ports {inverter3_pwm[1]}]
set_property PACKAGE_PIN L4 [get_ports {inverter3_pwm[2]}]
set_property PACKAGE_PIN L5 [get_ports {inverter3_pwm[3]}]
set_property PACKAGE_PIN P1 [get_ports {inverter3_pwm[4]}]
set_property PACKAGE_PIN N1 [get_ports {inverter3_pwm[5]}]

set_property PACKAGE_PIN K2 [get_ports {inverter4_pwm[0]}]
set_property PACKAGE_PIN L2 [get_ports {inverter4_pwm[1]}]
set_property PACKAGE_PIN L1 [get_ports {inverter4_pwm[2]}]
set_property PACKAGE_PIN P3 [get_ports {inverter4_pwm[3]}]
set_property PACKAGE_PIN P2 [get_ports {inverter4_pwm[4]}]
set_property PACKAGE_PIN J3 [get_ports {inverter4_pwm[5]}]

set_property PACKAGE_PIN N8 [get_ports {inverter5_pwm[0]}]
set_property PACKAGE_PIN P8 [get_ports {inverter5_pwm[1]}]
set_property PACKAGE_PIN N6 [get_ports {inverter5_pwm[2]}]
set_property PACKAGE_PIN N5 [get_ports {inverter5_pwm[3]}]
set_property PACKAGE_PIN K5 [get_ports {inverter5_pwm[4]}]
set_property PACKAGE_PIN J5 [get_ports {inverter5_pwm[5]}]

set_property PACKAGE_PIN M6 [get_ports {inverter6_pwm[0]}]
set_property PACKAGE_PIN R5 [get_ports {inverter6_pwm[1]}]
set_property PACKAGE_PIN R4 [get_ports {inverter6_pwm[2]}]
set_property PACKAGE_PIN P6 [get_ports {inverter6_pwm[3]}]
set_property PACKAGE_PIN P5 [get_ports {inverter6_pwm[4]}]
set_property PACKAGE_PIN L6 [get_ports {inverter6_pwm[5]}]

set_property PACKAGE_PIN J8 [get_ports {inverter7_pwm[0]}]
set_property PACKAGE_PIN K8 [get_ports {inverter7_pwm[1]}]
set_property PACKAGE_PIN M8 [get_ports {inverter7_pwm[2]}]
set_property PACKAGE_PIN M7 [get_ports {inverter7_pwm[3]}]
set_property PACKAGE_PIN AB21 [get_ports {inverter7_pwm[4]}]
set_property PACKAGE_PIN AB22 [get_ports {inverter7_pwm[5]}]

set_property PACKAGE_PIN AB18 [get_ports {inverter8_pwm[0]}]
set_property PACKAGE_PIN T16 [get_ports {inverter8_pwm[1]}]
set_property PACKAGE_PIN J6 [get_ports {inverter8_pwm[2]}]
set_property PACKAGE_PIN AA20 [get_ports {inverter8_pwm[3]}]
set_property PACKAGE_PIN AA19 [get_ports {inverter8_pwm[4]}]
set_property PACKAGE_PIN AB19 [get_ports {inverter8_pwm[5]}]

set_property PACKAGE_PIN B2 [get_ports {inverter_sts_a[0]}]
set_property PACKAGE_PIN E3 [get_ports {inverter_sts_a[1]}]
set_property PACKAGE_PIN E4 [get_ports {inverter_sts_a[2]}]
set_property PACKAGE_PIN F1 [get_ports {inverter_sts_a[3]}]
set_property PACKAGE_PIN F2 [get_ports {inverter_sts_a[4]}]
set_property PACKAGE_PIN E5 [get_ports {inverter_sts_a[5]}]
set_property PACKAGE_PIN F5 [get_ports {inverter_sts_a[6]}]
set_property PACKAGE_PIN H5 [get_ports {inverter_sts_a[7]}]

set_property PACKAGE_PIN W15 [get_ports {inverter_sts_b[0]}]
set_property PACKAGE_PIN C3 [get_ports {inverter_sts_b[1]}]
set_property PACKAGE_PIN D3 [get_ports {inverter_sts_b[2]}]
set_property PACKAGE_PIN C4 [get_ports {inverter_sts_b[3]}]
set_property PACKAGE_PIN D5 [get_ports {inverter_sts_b[4]}]
set_property PACKAGE_PIN G1 [get_ports {inverter_sts_b[5]}]
set_property PACKAGE_PIN H1 [get_ports {inverter_sts_b[6]}]
set_property PACKAGE_PIN B1 [get_ports {inverter_sts_b[7]}]

set_property PACKAGE_PIN Y19 [get_ports {inverter_sts_c[0]}]
set_property PACKAGE_PIN AA11 [get_ports {inverter_sts_c[1]}]
set_property PACKAGE_PIN AB11 [get_ports {inverter_sts_c[2]}]
set_property PACKAGE_PIN V11 [get_ports {inverter_sts_c[3]}]
set_property PACKAGE_PIN W11 [get_ports {inverter_sts_c[4]}]
set_property PACKAGE_PIN W12 [get_ports {inverter_sts_c[5]}]
set_property PACKAGE_PIN W13 [get_ports {inverter_sts_c[6]}]
set_property PACKAGE_PIN V15 [get_ports {inverter_sts_c[7]}]

set_property PACKAGE_PIN Y12 [get_ports {inverter_sts_d[0]}]
set_property PACKAGE_PIN Y13 [get_ports {inverter_sts_d[1]}]
set_property PACKAGE_PIN V13 [get_ports {inverter_sts_d[2]}]
set_property PACKAGE_PIN V14 [get_ports {inverter_sts_d[3]}]
set_property PACKAGE_PIN R17 [get_ports {inverter_sts_d[4]}]
set_property PACKAGE_PIN T17 [get_ports {inverter_sts_d[5]}]
set_property PACKAGE_PIN V16 [get_ports {inverter_sts_d[6]}]
set_property PACKAGE_PIN W16 [get_ports {inverter_sts_d[7]}]


connect_debug_port u_ila_0/probe0 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[0]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[1]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[2]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[3]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[4]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[5]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[6]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/device0_out[0]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/device0_out[1]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/device0_out[2]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[0]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[1]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[2]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[31]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[0]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[1]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[2]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[3]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[4]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[5]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[6]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[7]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[0]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[1]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[2]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[4]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe26 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe29 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe31 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe32 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe33 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe34 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe35 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe36 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe37 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe38 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[31]}]]
connect_debug_port u_ila_0/probe47 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[0]}]]
connect_debug_port u_ila_0/probe48 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[1]}]]
connect_debug_port u_ila_0/probe49 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[2]}]]
connect_debug_port u_ila_0/probe50 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe51 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[4]}]]
connect_debug_port u_ila_0/probe52 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe53 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe54 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe55 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe56 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe57 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe58 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe59 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe60 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe61 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe62 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe63 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe64 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe65 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe66 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe67 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe68 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe69 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe70 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe71 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[31]}]]

connect_debug_port u_ila_0/probe10 [get_nets [list amdc_revd_i/amdc_inverter_sts_mux_0/device0_b_out]]
connect_debug_port u_ila_0/probe11 [get_nets [list amdc_revd_i/amdc_inverter_sts_mux_0/device0_c_out]]



connect_debug_port u_ila_0/probe0 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[0]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[1]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[2]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[3]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[4]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[5]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[6]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[0]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[1]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[2]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[3]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[4]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[5]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[6]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[0]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[1]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[2]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[3]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[4]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[5]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[6]} {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/device0_a_out]]
connect_debug_port u_ila_0/probe4 [get_nets [list amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/device0_b_out]]
connect_debug_port u_ila_0/probe5 [get_nets [list amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/device0_c_out]]
connect_debug_port u_ila_0/probe6 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[0]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[1]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[2]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe26 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg0_reg_n_0_[31]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1[7]_i_1_n_0}]]
connect_debug_port u_ila_0/probe29 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1[15]_i_1_n_0}]]
connect_debug_port u_ila_0/probe30 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1[23]_i_1_n_0}]]
connect_debug_port u_ila_0/probe31 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1[31]_i_1_n_0}]]
connect_debug_port u_ila_0/probe32 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[0]}]]
connect_debug_port u_ila_0/probe33 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[1]}]]
connect_debug_port u_ila_0/probe34 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[2]}]]
connect_debug_port u_ila_0/probe35 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe36 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[4]}]]
connect_debug_port u_ila_0/probe37 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe38 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe39 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe40 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe41 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe42 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe43 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe44 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe45 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe46 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe47 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe48 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe49 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe50 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe51 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe52 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe53 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe54 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe55 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe56 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg1_reg_n_0_[31]}]]
connect_debug_port u_ila_0/probe57 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2[7]_i_1_n_0}]]
connect_debug_port u_ila_0/probe58 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2[15]_i_1_n_0}]]
connect_debug_port u_ila_0/probe59 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2[23]_i_1_n_0}]]
connect_debug_port u_ila_0/probe60 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2[31]_i_1_n_0}]]
connect_debug_port u_ila_0/probe61 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[0]}]]
connect_debug_port u_ila_0/probe62 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[1]}]]
connect_debug_port u_ila_0/probe63 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[2]}]]
connect_debug_port u_ila_0/probe64 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe65 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[4]}]]
connect_debug_port u_ila_0/probe66 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe67 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[6]}]]
connect_debug_port u_ila_0/probe68 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe69 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe70 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe71 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[10]}]]
connect_debug_port u_ila_0/probe72 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[11]}]]
connect_debug_port u_ila_0/probe73 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[12]}]]
connect_debug_port u_ila_0/probe74 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[13]}]]
connect_debug_port u_ila_0/probe75 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[14]}]]
connect_debug_port u_ila_0/probe76 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[15]}]]
connect_debug_port u_ila_0/probe77 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[16]}]]
connect_debug_port u_ila_0/probe78 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[17]}]]
connect_debug_port u_ila_0/probe79 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[18]}]]
connect_debug_port u_ila_0/probe80 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[19]}]]
connect_debug_port u_ila_0/probe81 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[20]}]]
connect_debug_port u_ila_0/probe82 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[21]}]]
connect_debug_port u_ila_0/probe83 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[22]}]]
connect_debug_port u_ila_0/probe84 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[23]}]]
connect_debug_port u_ila_0/probe85 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/slv_reg2_reg_n_0_[31]}]]
connect_debug_port u_ila_0/probe86 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[0]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe87 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[0]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe88 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[1]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe89 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[1]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe90 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[2]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe91 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[2]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe92 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[3]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe93 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[3]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe94 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[4]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe95 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[4]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe96 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[5]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe97 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[5]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe98 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[6]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe99 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[6]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe100 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[7]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe101 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_a_ext[7]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe102 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[0]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe103 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[0]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe104 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[1]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe105 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[1]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe106 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[2]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe107 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[2]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe108 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[3]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe109 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[3]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe110 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[4]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe111 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[4]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe112 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[5]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe113 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[5]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe114 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[6]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe115 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[6]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe116 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[7]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe117 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_b_ext[7]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe118 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[0]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe119 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[0]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe120 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[1]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe121 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[1]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe122 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[2]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe123 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[2]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe124 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[3]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe125 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[3]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe126 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[4]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe127 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[4]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe128 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[5]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe129 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[5]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe130 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[6]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe131 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[6]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe132 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[7]_INST_0_i_1_n_0}]]
connect_debug_port u_ila_0/probe133 [get_nets [list {amdc_revd_i/amdc_inverter_sts_mux_0/inst/amdc_inverter_sts_mux_v1_0_S00_AXI_inst/sts_c_ext[7]_INST_0_i_2_n_0}]]
connect_debug_port u_ila_0/probe134 [get_nets [list amdc_revd_i/amdc_dac_0/dac_cs]]
connect_debug_port u_ila_0/probe135 [get_nets [list amdc_revd_i/amdc_dac_0/dac_mosi]]
connect_debug_port u_ila_0/probe136 [get_nets [list amdc_revd_i/amdc_dac_0/dac_sclk]]

