#ifndef TASK_PRIORITY_H
#define TASK_PRIORITY_H

/* sys tasks */
#define SERIAL_TASK_PRIORITY tskIDLE_PRIORITY
#define CMD_UART_TASK_PRIORITY tskIDLE_PRIORITY
#define CMD_ETH_TASK_PRIORITY tskIDLE_PRIORITY

/* blink app */
#define BLINK_TASK_PRIORITY tskIDLE_PRIORITY
#define VSI_TASK_PRIORITY tskIDLE_PRIORITY

#endif // TASK_PRIORITY_H
